sonar.projectKey=python-ci-demo
sonar.projectName=Python CI Demo
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.exclusions=**/tests/**,**/venv/**,**/__pycache__/**,**/.github/**
sonar.tests=tests
sonar.python.version=3.11
